import assert from"node:assert/strict";import test from"node:test";import{createOAuthVaultCleanupWorker}from"../server/ai-media-studio/oauth/vault-cleanup-worker";import type{OAuthVaultCleanupItem,OAuthVaultCleanupRepository}from"../server/ai-media-studio/oauth/vault-cleanup-contracts";
const base={id:"11111111-1111-4111-8111-111111111111",scope:{ownerUserId:"owner",workspaceId:"workspace"},actorUserId:"actor",providerAccountId:"22222222-2222-4222-8222-222222222222",platform:"tiktok"as const,sessionId:"33333333-3333-4333-8333-333333333333",state:"leased"as const,attempt:1,maxAttempts:8,deletePass:0 as const,availableAt:"2026-07-21T12:00:00.000Z",quiescentUntil:"2026-07-21T12:00:00.000Z",leaseToken:"44444444-4444-4444-8444-444444444444",leaseOwner:"worker",leaseExpiresAt:"2026-07-21T12:05:00.000Z",leaseFencing:1};
function item(kind:OAuthVaultCleanupItem["kind"],id:string):OAuthVaultCleanupItem{const session=id.padEnd(8,"0").slice(0,8)+"-1111-4111-8111-111111111111";const common={...base,id,sessionId:session};if(kind==="pkce_verifier")return{...common,kind,reference:`vault://ai-media-studio/oauth-pkce/v1/${session}`,context:{purpose:"ai_media_oauth_pkce",...base.scope,actorUserId:"actor",providerAccountId:base.providerAccountId,platform:"tiktok",sessionId:session,expiresAt:"2026-07-21T12:10:00.000Z"}};
  const binding="55555555-5555-4555-8555-555555555555";if(kind==="authorization_code")return{...common,kind,reference:`vault://ai-media-studio/oauth-code/v1/${session}`,context:{purpose:"ai_media_oauth_authorization_code",...base.scope,actorUserId:"actor",providerAccountId:base.providerAccountId,platform:"tiktok",sessionId:session,tokenBindingId:binding,codeDigest:"a".repeat(64),expiresAt:"2026-07-21T12:10:00.000Z"}};
  return{...common,kind,reference:`vault://ai-media-studio/oauth-token/v1/${binding}`,context:{purpose:"ai_media_oauth_token",...base.scope,actorUserId:"actor",providerAccountId:base.providerAccountId,platform:"tiktok",sessionId:session,targetCredentialVersion:1,tokenBindingId:binding}};}
test("runOnce has no autostart, continues independent deletes, and records only safe codes",async()=>{const items=[item("pkce_verifier","10000000-1111-4111-8111-111111111111"),item("authorization_code","20000000-1111-4111-8111-111111111111")];const ack:string[]=[],fail:any[]=[];let claims=0;
  const repository:OAuthVaultCleanupRepository={async claimDue(){claims+=1;return items},async acknowledgeDelete(x){ack.push(x.id);return"verify_wait"},async recordFailure(x){fail.push(x);return"retry_wait"}};
  const worker=createOAuthVaultCleanupWorker({repository,pkceVault:{async put(){return""},async read(){return""},async delete(){throw new Error("raw-secret-sentinel")}},authorizationCodeVault:{async putOnce(){return""},async read(){return""},async delete(){}},tokenVault:{async putOnce(){throw 0},async find(){return undefined},async readDescriptor(){throw 0},async delete(){}} ,clock:()=>new Date("2026-07-21T12:00:00.000Z")});
  assert.equal(claims,0);const result=await worker.runOnce({limit:2,leaseOwner:"worker"});assert.equal(result.claimed,2);assert.equal(result.failed,1);assert.deepEqual(ack,[items[1].id]);assert.equal(fail[0].errorCode,"vault_rejected");assert.equal(JSON.stringify(fail).includes("raw-secret-sentinel"),false);
});
test("delete then lost acknowledgement is safely repeated; second acknowledged pass completes",async()=>{const target=item("token_credential","30000000-1111-4111-8111-111111111111");let deletes=0,acks=0;const repository:OAuthVaultCleanupRepository={async claimDue(){return[target]},async acknowledgeDelete(){acks+=1;return acks===1?undefined:acks===2?"verify_wait":"completed"},async recordFailure(){return"retry_wait"}};
  const token={async putOnce(){throw 0},async find(){return undefined},async readDescriptor(){throw 0},async delete(){deletes+=1}};const worker=createOAuthVaultCleanupWorker({repository,pkceVault:{async put(){return""},async read(){return""},async delete(){}},authorizationCodeVault:{async putOnce(){return""},async read(){return""},async delete(){}},tokenVault:token,clock:()=>new Date("2026-07-21T12:00:00.000Z")});
  assert.equal((await worker.runOnce({limit:1,leaseOwner:"worker"})).leaseLost,1);assert.equal((await worker.runOnce({limit:1,leaseOwner:"worker"})).verifyWait,1);assert.equal((await worker.runOnce({limit:1,leaseOwner:"worker"})).completed,1);assert.equal(deletes,3);
});
test("runOnce records timeout and invalid-obligation codes without leaking details",async()=>{const failures:any[]=[];const invalid={...item("pkce_verifier","40000000-1111-4111-8111-111111111111"),kind:"unknown"}as unknown as OAuthVaultCleanupItem;let claims=0;
  const repository:OAuthVaultCleanupRepository={async claimDue(){claims+=1;return claims===1?[item("pkce_verifier","50000000-1111-4111-8111-111111111111")]:[invalid]},async acknowledgeDelete(){return"completed"},async recordFailure(value){failures.push(value);return"retry_wait"}};
  const worker=createOAuthVaultCleanupWorker({repository,pkceVault:{async put(){return""},async read(){return""},async delete(){await new Promise(()=>{})}},authorizationCodeVault:{async putOnce(){return""},async read(){return""},async delete(){}},tokenVault:{async putOnce(){throw 0},async find(){return undefined},async readDescriptor(){throw 0},async delete(){}},operationBudgetMs:5});
  await worker.runOnce({limit:1,leaseOwner:"worker"});await worker.runOnce({limit:1,leaseOwner:"worker"});assert.equal(failures[0].errorCode,"vault_timeout");assert.equal(failures[1].errorCode,"invalid_obligation");
});
