import {
  AI_MEDIA_STUDIO_AGENT_ROUTE,
  aiMediaStudioAgentSnapshotSchema,
  type AiMediaStudioAgentSnapshot,
  type AiMediaStudioAgentWorkItem,
} from "../../shared/ai-media-studio-agent";
import { INITIAL_CREATOR_CANARY_PROFILE } from "../../shared/ai-media-studio-launch-plan-profile";
import type { SourceSyncTask } from "./sources/source-sync-scheduler";

const AGENT_DATA_AS_OF = "2026-07-22T20:11:43.000Z" as const;

const workItems: readonly AiMediaStudioAgentWorkItem[] = [
  {
    id: "ams-agent-pr27-terminal-evidence",
    title: "HeyGen V3 terminal evidence boundary",
    owner: "AI Media Studio backend squad",
    state: "review",
    branch: "codex/ai-media-studio-heygen-terminal-evidence",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/112",
    acceptance: [
      "Provider-authoritative terminal state is exact-account and credential bound",
      "Completed MP4 ingest uses a renewable provider artifact identity",
      "Committed money is never falsely refunded",
    ],
    mergeGate: "Independent checker and App QA report no P0-P2; PostgreSQL, full suite, typecheck and build pass.",
    evidence: ["PR #112", "PostgreSQL 16: 4/4", "Full suite: 657 passed, 0 failed, 24 skipped of 681", "App QA: P0=0, P1=0, P2=0"],
    blockers: [],
    nextAction: "Keep this slice unmounted until production composition and staging gates pass.",
  },
  {
    id: "ams-agent-pr28-control-pane",
    title: "Dedicated AI Media Studio Agent control pane",
    owner: "AI Media Studio product squad",
    state: "review",
    branch: "codex/ai-media-studio-agent-control",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/115",
    acceptance: [
      "Agents Office exposes one dedicated AI Media Studio Agent",
      "The agent area shows owners, states, PRs, evidence, blockers and merge gates",
      "The pane performs no deployment, spend, migration or provider action",
    ],
    mergeGate: "Focused contracts/UI/routes, TypeScript, build, independent checker and App QA all pass before the draft PR is presented as reviewed.",
    evidence: ["Draft PR #115", "Control 5/5 + HTTP routes 4/4; full suite 662 passed, 0 failed, 24 skipped", "TypeScript and production build pass", "Checker and App QA recheck: P0=P1=P2=0"],
    blockers: [],
    nextAction: "Keep the pane read-only and begin the separately reviewed inert production-composition slice.",
  },
  {
    id: "ams-agent-pr29-production-composition",
    title: "Inert HeyGen V3 production composition",
    owner: "AI Media Studio runtime squad",
    state: "review",
    branch: "codex/ai-media-studio-production-composition",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/116",
    acceptance: [
      "Compose admitted submit, terminal observation and renewable ingest without autostart",
      "Exact account, credential and tenant mismatches fail before provider I/O",
      "Construction performs no database, network, storage or spend action",
    ],
    mergeGate: "Composition tests prove zero construction I/O and fail-closed behavior; no route, timer or loop is mounted.",
    evidence: ["Draft PR #116", "Focused tenant/composition/asset regressions: 29/29", "Full suite: 666 passed, 0 failed, 24 skipped", "Checker and App QA recheck: P0=P1=P2=0"],
    blockers: [],
    nextAction: "Keep the runtime unmounted and prepare the ordered staging migration/restart rehearsal for explicit approval.",
  },
  {
    id: "ams-agent-durable-roster-plan",
    title: "Durable roster to ten-slots-per-avatar bridge",
    owner: "AI Media Studio planning squad",
    state: "review",
    branch: "codex/ai-media-studio-durable-roster-plan-bridge",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/136",
    acceptance: [
      "One 5–10 avatar onboarding transaction creates exactly ten blocked durable slots per avatar",
      "Exact replay is tenant-safe and never duplicates or partially persists a plan",
      "The bridge creates no budget reservation, render job, outbox command, provider call or spend",
    ],
    mergeGate: "Focused and PostgreSQL race/rollback evidence, TypeScript, build, independent checker and App QA must pass before the draft PR is ready.",
    evidence: [
      "Draft PR #131 preserves the reviewed 22-pair migration baseline",
      "Three independent design/security audits selected the existing PR19 plan and slot tables",
      "Focused roster/control checks, authenticated HTTP routes, TypeScript and production build pass",
      "Owned ephemeral PostgreSQL 16 full-chain proof passes 1/1 for 5→50, 10→100, replay, concurrency, tenant isolation and rollback",
      "Independent checker and App QA pass with P0=P1=P2=0 and no change warnings",
      "Draft PR #136 preserves the reviewed checkpoint stacked on draft PR #131",
    ],
    blockers: ["Merge, migration rehearsal, one-video sandbox, batch spend and deployment remain separately blocked"],
    nextAction: "Keep PR #136 unmerged until the stacked chain is reviewed; request separate approvals before staging, HeyGen sandbox, spend or Replit deployment.",
  },
  {
    id: "ams-agent-durable-script-batch",
    title: "Durable production script batch workbench",
    owner: "AI Media Studio content planning squad",
    state: "review",
    branch: "codex/ai-media-studio-durable-script-batch",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/141",
    acceptance: [
      "Exactly ten eligible Kong sources prepare one durable draft script for every blocked slot",
      "Five to ten creators remain grouped into exactly ten no-spend slots each",
      "Replay, source refresh, tenant isolation and partial failure fail closed without duplicate scripts",
      "Legacy generation cannot bypass daily-plan admission, and no provider, budget, render or outbox side effect occurs",
    ],
    mergeGate: "PostgreSQL race/rollback/source-refresh proof, TypeScript, build, independent checker and App QA must pass before a stacked draft PR is ready.",
    evidence: [
      "Draft PR #136 preserves the reviewed durable 5→50 and 10→100 roster-plan checkpoint",
      "Three independent product, operations and architecture audits selected the provider-neutral prepare-only batch slice",
      "Backend and frontend makers had non-overlapping ownership in an isolated worktree",
      "Focused/UI/HTTP tests, TypeScript, production build and the refreshed codebase map pass",
      "Owned PostgreSQL 16 applied the exact 22-pair chain and proved 5→50, 10→100, replay/concurrency, tenant isolation, source refresh, rollback and zero launch side effects",
      "Independent checker recheck is P0=P1=P2=0 after one fixed UI error-message finding",
      "App QA is P0=P1=P2=0 after the optional GET preserved safe server error text",
      "Mergeable draft PR #141 is stacked on reviewed draft PR #136",
    ],
    blockers: ["Merge, migration rehearsal, provider sandbox, batch spend and deployment remain separately blocked", "The inherited Clippers chunk warning blocks deployment; no deployment is requested"],
    nextAction: "Keep draft PR #141 unmerged while the stacked chain is reviewed; request separate approval before staging, HeyGen sandbox, spend or Replit deployment.",
  },
  {
    id: "ams-agent-launch-readiness",
    title: "Durable script review and launch readiness",
    owner: "AI Media Studio content approval squad",
    state: "review",
    branch: "codex/ai-media-studio-launch-readiness",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/144",
    acceptance: [
      "Every selected 5–10 × 10 creative exposes and seals Video Title, angle, hook, script, CTA, caption, hashtags and SEO",
      "One tenant-locked whole-batch transition approves only scripts and their selected/current variants",
      "Approval revalidates exact batch, source content, status, rights and moderation without creating launch or provider work",
    ],
    mergeGate: "Focused, HTTP and PostgreSQL proof, TypeScript, build, independent checker, security and App QA must pass before the draft GitHub checkpoint.",
    evidence: [
      "Draft PR #144 is stacked on draft PR #141",
      "Focused checks 20/20; authenticated HTTP routes 2/2; owned PostgreSQL 16 exact-chain harness 1/1",
      "Full suite: 722 passed, one inherited PR26 wording-regex failure and 40 controlled PostgreSQL-only skips of 763",
      "TypeScript and production build pass",
      "Independent checker, security and App QA: P0=P1=P2=P3=0",
    ],
    blockers: [
      "Merge, migration rehearsal, governance and launch authority, one-video sandbox, batch spend and deployment remain separately blocked",
      "The inherited Clippers chunk warning blocks deployment; no deployment is requested",
    ],
    nextAction: "Keep draft PR #144 unmerged and implement the offline authority/admission preflight as a separately reviewed slice; do not call HeyGen or authorize spend.",
  },
  {
    id: "ams-agent-offline-launch-preflight",
    title: "Offline launch preflight and exact approval bridge",
    owner: "AI Media Studio launch safety squad",
    state: "review",
    branch: "codex/ai-media-studio-offline-launch-preflight",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/146",
    acceptance: [
      "The approved 5–10 × 10 batch is revalidated from exact tenant, source, creative and approval metadata",
      "One authenticated read-only observation reports all 14 launch gates without minting authority",
      "Creator confirmations and approval success belong only to the exact visible batch identity",
      "No provider call, budget reservation, render, outbox, migration, deployment or spend is authorized",
    ],
    mergeGate: "Focused, HTTP, PostgreSQL, TypeScript, build, independent checker, security and App QA must pass with no P0-P3 before the draft checkpoint is ready.",
    evidence: [
      "Draft PR #146 is stacked on draft PR #144",
      "Focused checks 54/54; authenticated HTTP routes 2/2; owned PostgreSQL 16 exact 22-pair chain 1/1",
      "Full suite: 749 passed, one inherited PR26 wording-regex failure and 41 controlled skips of 791",
      "TypeScript and production build pass",
      "Independent checker, security and App QA final gates: P0=P1=P2=P3=0",
    ],
    blockers: [
      "Merge, migration rehearsal, live provider verification, authority/evidence, one-video sandbox, batch spend and deployment remain separately blocked",
      "The inherited Clippers chunk warning blocks deployment; no deployment is requested",
    ],
    nextAction: "Keep draft PR #146 unmerged; obtain separate approvals before staging, a one-video HeyGen sandbox, any spend, or Replit deployment.",
  },
  {
    id: "ams-agent-one-video-sandbox-readiness",
    title: "One-video sandbox readiness packet and offline runtime proof",
    owner: "AI Media Studio sandbox readiness squad",
    state: "review",
    branch: "codex/ai-media-studio-one-video-sandbox-readiness",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/147",
    acceptance: [
      "One explicitly selected slot from a genuine approved 5 × 10 batch exposes an authenticated read-only 9:16 readiness packet",
      "A disposable exact-chain PostgreSQL rehearsal drives exactly one slot through fake submit, terminal completion and durable owned ingest with zero publishing",
      "Generation, provider submission, admission, spend and every effect remain false; no real provider, migration or deployment action occurs",
    ],
    mergeGate: "Focused, HTTP, browser, PostgreSQL, TypeScript, build, independent checker, security and App QA pass with P0=P1=P2=P3=0 before the draft checkpoint is ready.",
    evidence: [
      "Draft PR #147 is stacked on draft PR #146",
      "A genuine approved 5 × 10 fixture keeps all 50 scripts approved while exactly one selected slot completes the fake-provider runtime rehearsal",
      "Focused 59/59; authenticated routes 4/4; browser 1/1; owned PostgreSQL 16 exact 22-pair chain 1/1",
      "Full suite: 811/812 passed; the only failure is the inherited PR26 wording regex. TypeScript, production build and diff hygiene pass",
      "Independent checker, security and App QA final gates: P0=P1=P2=P3=0 after one P3 test correction",
    ],
    blockers: [
      "Merge, named staging migration rehearsal, live HeyGen credential/account/quota verification, maximum quote, owned storage, callbacks and explicit one-video cost approval remain separately blocked",
      "The later 5 × 10 canary spend and Replit deployment require separate approvals; no provider call or spend is authorized",
      "The inherited Clippers chunk warning blocks deployment; no deployment is requested",
    ],
    nextAction: "Keep draft PR #147 unmerged; accept the HeyGen API key only through the approved secret manager plus 5–10 avatar/voice IDs, and do not call HeyGen until live checks and Robert's explicit one-video cost approval pass.",
  },
  {
    id: "ams-agent-static-heygen-onboarding",
    title: "Secure static HeyGen credential and roster onboarding",
    owner: "AI Media Studio provider onboarding squad",
    state: "review",
    branch: "codex/ai-media-studio-heygen-onboarding-readiness",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/148",
    acceptance: [
      "Persist only an approved secret-manager reference and digest, never the HeyGen API key value",
      "Accept 5–10 avatar and voice ID pairs as pending verification and create exactly ten blocked no-spend slots per avatar",
      "Expose authenticated read-only onboarding readiness while pending resources remain inactive and non-selectable",
    ],
    mergeGate: "Static credential, roster, HTTP, browser, PostgreSQL, TypeScript, build, checker, security and App QA evidence must pass with no P0-P3 before the draft checkpoint is ready.",
    evidence: [
      "Draft PR #148 is stacked on draft PR #147",
      "Final App QA targeted run passes 44/44; TypeScript, production build, codebase map and diff hygiene pass",
      "Disposable PostgreSQL 16 exact PR1–PR27 chain plus pending PR28 forward, rotation and rollback guard passes 1/1",
      "Independent checker, security and App QA final gates: P0=P1=P2=P3=0",
    ],
    blockers: [
      "The API key has not been placed in the deployment secret manager and no live HeyGen verification has run",
      "The pending PR28 migration is outside the manifest and unapplied; promotion and application require separate approval",
      "One-video generation, 5 × 10 batch spend, publishing and Replit deployment remain separately blocked",
    ],
    nextAction: "Keep draft PR #148 unmerged; Robert places the API key only in the approved secret manager and supplies 5–10 avatar/voice IDs, then separately approve read-only live verification before any quote or generation.",
  },
  {
    id: "ams-agent-one-video-execution-control",
    title: "Inert one-video verification and execution control",
    owner: "AI Media Studio provider execution squad",
    state: "review",
    branch: "codex/ai-media-studio-one-video-execution-control",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/149",
    acceptance: [
      "Pin one reviewed official HeyGen API profile behind provider-neutral verification and render contracts",
      "Bind credential, avatar, voice, approved script, vertical format and maximum quote to exactly one public slot",
      "Keep verification, quote preparation and human approval distinct while execution, provider calls and spend remain disabled",
      "Define fail-closed handling for credential rotation, stale evidence, ambiguous submit, callback fallback, ingest and actual-cost settlement",
    ],
    mergeGate: "Official-provider documentation audit, focused and PostgreSQL evidence, TypeScript, build, independent checker, security and App QA must pass with no P0-P3 before a stacked draft PR is ready.",
    evidence: [
      "Draft PR #149 is stacked on reviewed draft PR #148",
      "Focused control/client/UI 58/58, one-video control 9/9, isolated browser 1/1, TypeScript and production build pass",
      "Full serial AI Media Studio suite: 804 passed, one inherited PR26 wording-regex failure and 43 controlled skips of 848",
      "Independent checker, security and App QA final gates: P0=P1=P2=P3=0 after the V3 avatar-look correction",
    ],
    blockers: [
      "No API key, live account, avatar look, voice, storage or callback has been verified",
      "Immutable exact static-credential verification and account-specific maximum quote evidence do not exist yet",
      "Provider verification, any migration apply, one-video POST, spend, publishing and Replit deployment require separate approvals",
    ],
    nextAction: "Keep draft PR #149 unmerged; Robert supplies the API key only through the deployment secret manager plus 5–10 avatar-look/voice ID pairs, then separately approve read-only live verification before quote or generation.",
  },
  {
    id: "ams-agent-heygen-verification-evidence",
    title: "Immutable HeyGen V3 verification evidence",
    owner: "AI Media Studio credential verification squad",
    state: "review",
    branch: "codex/ai-media-studio-heygen-verification-evidence",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/154",
    acceptance: [
      "Persist immutable tenant- and credential-version-bound account verification evidence without credential material",
      "Bind every configured avatar resource to an exact HeyGen V3 avatar look and keep parent-group consent/status evidence separate",
      "Bind every configured voice to an exact verified V3 voice response and make rotation stale by construction",
      "Keep provider transport, secret resolution, account activation, migration application, spend and rendering disabled until separate approval",
    ],
    mergeGate: "Draft PR #154 stays unmerged; live verification, migration application, quote, spend, generation and deployment remain separate Robert approvals.",
    evidence: [
      "Draft PR #154 is stacked on draft PR #149 with the PR29 migration outside the manifest and unapplied",
      "Provider 25/25, coordinator 4/4, migration 7/7, disposable PostgreSQL 16 1/1, TypeScript and production build pass",
      "Final checker, security and App QA report P0-P3 clean; full suite records 840 pass, one inherited PR26 mismatch and 44 controlled skips",
    ],
    blockers: [
      "No API key has been placed in the deployment secret manager and no provider request is approved",
      "No live account, avatar look, parent group, voice, quota, wallet or billing evidence exists",
      "Migration application, credential resolution, provider verification, account activation, quote, generation, spend and Replit deployment require separate approvals",
    ],
    nextAction: "Keep draft PR #154 unmerged; Robert places the API key only in the deployment secret manager, provides 5–10 exact avatar-look/voice pairs, then separately approves live read-only verification.",
  },
  {
    id: "ams-agent-one-video-verification-read-model",
    title: "Exact one-video HeyGen verification read model",
    owner: "AI Media Studio read-model squad",
    state: "review",
    branch: "codex/ai-media-studio-one-video-verification-read-model",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/156",
    acceptance: [
      "Project verified state only from the exact immutable PR29 account, avatar-look and voice evidence graph",
      "Fail closed for expiry, credential rotation, tenant or plan mismatch, and incomplete resource evidence",
      "Keep the authenticated endpoint GET-only, redact provider-native identities and leave execute, spend, publishing and every effect disabled",
      "Prove the projection with focused tests and a disposable PostgreSQL 16 integration fixture for the initial 5 avatars × 10 videos shape",
    ],
    mergeGate: "Focused, PostgreSQL, TypeScript, build, independent checker, security and App QA evidence must pass with no P0-P3 before a stacked draft PR is ready.",
    evidence: [
      "Read-only control, data, test and App QA audits identified the exact PR29 evidence projection gap",
      "Focused control and authenticated route checks pass 12/12; disposable PostgreSQL 16 exact 5 x 10 and 10 x 10 proof passes 2/2",
      "TypeScript and production build pass; independent checker, security and App QA are P0-P3 clean",
    ],
    blockers: [
      "The PR29 migration remains pending and unapplied; this read model is stacked after that migration",
      "No API key, live HeyGen verification, quote, spend, generation, publishing or deployment is authorized",
    ],
    nextAction: "Keep this stacked checkpoint unmerged; Robert later supplies the API key only through the secret manager and separately approves live read-only verification.",
  },
  {
    id: "ams-agent-secure-heygen-setup-runtime",
    title: "Guided secure HeyGen setup and explicit verification runtime",
    owner: "Dedicated HeyGen onboarding and verification agents",
    state: "review",
    branch: "codex/ai-media-studio-secure-heygen-setup-runtime",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/161",
    acceptance: [
      "Robert adds the API key only as AI_MEDIA_STUDIO_SECRET_HEYGEN_API_KEY in the deployment secret manager",
      "The browser registers only a fixed allowlisted reference and accepts 5–10 avatar-look and voice pairs for exactly ten blocked videos each",
      "Live verification is a separate explicitly authorized GET-only action with immutable evidence and no generation or spend",
      "The action center shows the current safe next step without requesting or exposing credential material",
    ],
    mergeGate: "Focused, PostgreSQL, TypeScript, build, independent checker, security and App QA evidence must pass before a stacked draft PR is ready.",
    evidence: [
      "Draft PR #161 preserves the secure setup checkpoint on GitHub",
      "Focused setup suite 22/22, PostgreSQL 1/1, browser 1/1 and production build passed",
      "Independent security and App QA reviews report P0=P1=P2=P3=0; checker found no functional P0/P1",
      "Public setup contracts reject API keys, caller-selected secret references and provider account IDs",
    ],
    blockers: [
      "PR28 and PR29 migrations remain pending and unapplied",
      "No live verification call is authorized; quote, generation, spend, publishing and deployment remain separate gates",
      "Draft PR #165 now closes quote-to-human approval binding, but it remains unmerged in the stacked chain",
    ],
    nextAction: "Keep draft PR #161 unmerged; then Robert supplies the secret through the deployment secret manager and the avatar/voice IDs through the guided roster before separately authorizing GET-only verification.",
  },
  {
    id: "ams-agent-quote-bound-human-approval",
    title: "Exact maximum-quote to human-approval binding",
    owner: "Quote authority, schema, security and App QA agents",
    state: "review",
    branch: "codex/ai-media-studio-quote-bound-approval",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/165",
    acceptance: [
      "Robert's decision is durably bound to one exact latest quote, amount, USD currency, expiry and server-derived render specification",
      "A newer quote, changed subject, credential rotation, expiry or tenant mismatch makes the prior approval stale",
      "Legacy unbound approvals never satisfy snapshot, admission or the one-video execution read model",
      "Approval records no provider, secret, reservation, render, outbox, spend, publishing, migration or deployment effect",
    ],
    mergeGate: "Draft PR #165 is open and stacked on PR #161; it must remain unmerged until the dependency chain, checker, security and App QA gates stay green.",
    evidence: [
      "PR #165 binds human approval to exact quote evidence identity, revision, digest, amount, USD currency, expiry and server render-spec digest",
      "Focused suite: 50 passed and 3 optional route tests skipped because the local worktree lacks optional route dependency",
      "Sandbox browser rerun outside sandbox passed 1/1; PR30 isolated PostgreSQL harness passed 1/1; agent control passed 5/5; build passed",
      "The staged diff secret scan found no new secret/token/private-key patterns",
    ],
    blockers: [
      "No authoritative account-specific HeyGen quote provider is installed, so no amount may be fabricated",
      "PR28 and PR29 migrations remain pending and unapplied",
      "No generation, spend, publishing, migration apply or Replit deployment is authorized",
    ],
    nextAction: "Keep draft PR #165 unmerged; next implement an authoritative account-specific quote provider and keep generation, spend, publishing, migration apply and Replit deployment behind separate Robert approvals.",
  },
  {
    id: "ams-agent-heygen-account-maximum-quote",
    title: "Fail-closed HeyGen account maximum-quote adapter",
    owner: "Quote provider, documentation, security and review agents",
    state: "review",
    branch: "codex/ai-media-studio-heygen-account-quote",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/166",
    acceptance: [
      "Accept only an exact server-locked subject, render specification, account, credential version, database time and idempotency key",
      "Never convert public rates, script length or wallet balance into authoritative quote evidence",
      "Return an explicit unavailable outcome when HeyGen provides no account-specific pre-generation quote",
      "Perform no network, secret, provider POST, reservation, render, outbox, spend, publishing, migration or deployment effect",
    ],
    mergeGate: "Draft PR #166 stays stacked on PR #165; a future quoted outcome requires authoritative account terms and a separately reviewed durable quote coordinator.",
    evidence: [
      "Official HeyGen user, pricing, create-video and documentation-index sources expose no pre-generation quote endpoint",
      "Strict locked-request and quote-outcome suite passes 22/22",
      "Independent checker reports P0=P1=P2=P3=0 and production build passes",
      "PR #165 production approval wiring was corrected and independently rechecked before PR #166 was opened",
    ],
    blockers: [
      "Authoritative account-specific HeyGen pre-generation quote terms remain unavailable",
      "No maximum-quote evidence may be minted from public prices or estimated script duration",
      "Generation, spend, publishing, migration apply and Replit deployment remain separately blocked",
    ],
    nextAction: "Keep draft PR #166 unmerged; obtain authoritative account quote terms before adding the durable quote coordinator, then separately approve one live GET-only verification and one-video sandbox.",
  },
  {
    id: "ams-agent-quote-readiness",
    title: "Provider-neutral maximum-quote readiness",
    owner: "Quote readiness maker, checker and App QA agents",
    state: "review",
    branch: "codex/ai-media-studio-quote-readiness",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/168",
    acceptance: [
      "Launch preflight and exact one-video control expose the same strict readiness states and safe next actions",
      "Exact quote evidence cannot be impersonated by capability or explanatory readiness",
      "HeyGen reports account-specific terms required without a provider call, secret resolution or estimated cost",
      "No quote request, approval, reservation, render, outbox, spend, publishing, migration or deployment effect is introduced",
    ],
    mergeGate: "Focused contracts, repositories, client and UI tests, production build, independent checker and App QA must pass before the stacked draft PR is ready.",
    evidence: [
      "Both read models use one provider-neutral capability registry and strict public quote-readiness schema",
      "The exact approval control remains enabled only by current server-attested quote and render-spec evidence",
      "Production HeyGen composition uses the inert fail-closed adapter from draft PR #166",
      "Draft PR #168 preserves the checkpoint; independent checker and App QA report P0=P1=P2=P3=0 and the production build passes",
    ],
    blockers: [
      "Authoritative account-specific HeyGen pre-generation quote terms remain unavailable",
      "The one-shot executor remains uninstalled and provider I/O remains disabled",
      "Generation, spend, publishing, migration apply and Replit deployment remain separately blocked",
    ],
    nextAction: "Keep draft PR #168 unmerged; obtain authoritative account terms before implementing durable quote acquisition, then request separate approvals for live verification and one-video sandbox generation.",
  },
  {
    id: "ams-agent-one-video-held-admission",
    title: "One-video held admission and expiry safety",
    owner: "Admission, database safety, authorization, UI, security and App QA agents",
    state: "review",
    branch: "codex/ai-media-studio-one-video-held-admission",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/169",
    acceptance: [
      "An authenticated personal-workspace operator can request one exact held admission using public CAS keys only",
      "The server derives all internal identifiers, authority, budget, versions, money and expiry before a locked revalidation",
      "Admission creates only a reserved budget record plus sealed render/outbox work in held states",
      "Expired never-activated held admissions release budget exactly once through reviewed database evidence",
      "Provider activation, secret resolution, external spend, rendering, publishing, migration apply and deployment remain unavailable",
    ],
    mergeGate: "Code review gates are clean; a real PostgreSQL observation/replay rehearsal is still required before PR #169 can merge, and migration apply remains separately approval-gated.",
    evidence: [
      "PR #169 implementation checkpoint commit c9d7b63d",
      "Maker focused verification: 83/83 passed",
      "Independent checker verification: 62/62 passed",
      "App QA release gate: 13/13 passed",
      "Final review reports P0=P1=P2=P3=0",
    ],
    blockers: [
      "A real PostgreSQL observation/replay rehearsal remains required before merge",
      "Pending migrations remain unapplied and require separate review and explicit migration approval",
      "Live HeyGen verification and authoritative account-specific quote evidence remain absent",
      "Provider activation, external spend, generation, publishing and Replit deployment remain separately blocked",
    ],
    nextAction: "Keep PR #169 unmerged until the real PostgreSQL observation/replay rehearsal passes; do not apply migrations, call HeyGen, authorize spend, publish or deploy.",
  },
  {
    id: "ams-agent-roster-mutation-hardening",
    title: "HeyGen roster mutation boundary hardening",
    owner: "Roster API security maker, independent checker and App QA",
    state: "review",
    branch: "codex/ai-media-studio-roster-mutation-hardening",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/170",
    acceptance: [
      "Every roster mutation requires a strict real authenticated session plus exact same-origin JSON",
      "Development fallback identities, cross-site requests and private fields are rejected before persistence",
      "Roster mutation handling creates no provider call, secret resolution or external spend effect",
    ],
    mergeGate: "Code review gates are clean for draft PR #170; keep the stacked chain unmerged until the required PostgreSQL rehearsal and separate external approvals are complete.",
    evidence: [
      "Draft PR #170 checkpoint commit 954bd9f7",
      "Root focused verification: 41/41 passed; TypeScript and production build passed",
      "Independent checker recheck: 14/14 passed and P0=P1=P2=P3=0",
      "App QA: 43/43 relevant checks and 17/17 correction recheck passed",
    ],
    blockers: [
      "No real PostgreSQL rehearsal or browser visual QA has been performed for this checkpoint",
      "The stacked migration chain remains unapplied and requires separate explicit approval",
      "Live HeyGen calls, spend, publishing, migrations and deployment remain unauthorized",
    ],
    nextAction: "Keep PR #170 draft and unmerged; next rehearse the approved database chain before requesting any live HeyGen verification, cost approval, canary generation or deployment.",
  },
  {
    id: "ams-agent-kong-source-to-script",
    title: "Kong-owned source eligibility and script preview bridge",
    owner: "AI Media Studio source governance squad",
    state: "review",
    branch: "codex/ai-media-studio-kong-source-to-script",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/172",
    acceptance: [
      "An injected provider-neutral Kong-owned reader adapter covers all eight requested source categories without construction I/O",
      "Tenant-scoped source review requires exact content identity before rights, moderation and acceptance can change",
      "Only accepted owned-or-licensed and moderation-approved sources can produce a source-to-script preview",
      "The browser can send only Studio source IDs and bounded script options, never provider IDs, cursors, source payloads or native metadata",
      "The Automation UI exposes explicit review decisions and only redacted title, hook and caption previews",
      "Eligibility review and script preview create no durable script, orchestration run, render, outbox, video-provider, secret, spend, publishing, migration or deployment effect",
    ],
    mergeGate: "Code review gates are clean for draft PR #172; keep the stacked chain unmerged until production reader, durable scheduling and later live-provider gates are separately reviewed and approved.",
    evidence: [
      "Draft PR #172 checkpoint commit 2cf5ec81, stacked on draft PR #171",
      "Root focused non-HTTP verification 75/75 and authenticated HTTP verification 18/18 passed",
      "TypeScript, production build, codebase map and diff hygiene passed",
      "Independent checker and App QA: P0=P1=P2=P3=0 with no remaining actionable finding",
    ],
    blockers: [
      "No production Kong reader implementation or durable source scheduler is configured or activated",
      "The preview is intentionally not a durable script-batch approval and does not admit render work",
      "HeyGen, spend, publishing, migrations and deployment remain separately blocked",
    ],
    nextAction: "Keep PR #172 draft and unmerged; next implement and rehearse the production Kong reader, durable scheduler and source-to-batch consumer without enabling HeyGen, spend, publishing or deployment.",
  },
  {
    id: "ams-agent-source-automation-sync",
    title: "Tenant-safe source automation sync",
    owner: "AI Media Studio source automation squad",
    state: "review",
    branch: "codex/ai-media-studio-source-automation-sync",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/171",
    acceptance: [
      "Server-owned adapters normalize source records without trusting caller-selected provider or storage authority",
      "Each tenant-scoped sync is bounded and deduplicated so replay cannot multiply source records or cross tenant boundaries",
      "The public source projection redacts provider payloads, private identifiers and internal synchronization metadata",
      "Synchronization creates no script, render, video-provider, secret, spend, publishing, migration or deployment effect",
    ],
    mergeGate: "Code review gates are clean for draft PR #171; keep the stacked chain unmerged until a real Kong adapter, durable rehearsal and later orchestration gates are separately reviewed.",
    evidence: [
      "Draft PR #171 checkpoint commit 2452b955",
      "Root final source, HTTP and regression verification: 44/44 passed",
      "Independent checker: 26/26 plus HTTP 4/4 passed; P0=P1=P2=P3=0",
      "Independent security recheck: 17/17 passed; P0=P1=P2=P3=0",
      "App QA final regression gate: 36/36 passed; TypeScript and production build passed",
    ],
    blockers: [
      "No production Kong source adapter or automatic scheduler is configured or activated",
      "Source-to-script orchestration, rights/moderation approval and production PostgreSQL rehearsal remain separate work",
      "Video generation, HeyGen, spend, publishing, migrations and deployment remain separately blocked",
    ],
    nextAction: "Keep PR #171 draft and unmerged; next add one reviewed Kong source adapter and source-to-script orchestration without enabling video generation, spend, publishing or deployment.",
  },
  {
    id: "ams-agent-source-to-batch-automation",
    title: "Durable source-to-batch script automation",
    owner: "AI Media Studio source automation squad",
    state: "review",
    branch: "codex/ai-media-studio-source-to-batch-automation",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/173",
    acceptance: [
      "A strict same-origin source automation endpoint prepares the current 5-10 creator batch with an empty browser body only",
      "Server-owned idempotency and adapter selection constrain durable script preparation to eligible kong-owned-catalog source rows",
      "Prepared and approved batch replays do not create duplicate scripts or mutate approval/render state",
      "The Automation UI exposes a no-credits batch preparation control and refreshes source plus production-batch state",
      "The boundary records no script approval, render, outbox, video-provider, secret, spend, publishing, migration or deployment effect",
    ],
    mergeGate: "Draft PR #173 stays stacked on PR #172; keep it unmerged until checker/App QA review, production reader, durable scheduling and later live-provider gates are separately reviewed and approved.",
    evidence: [
      "Source-to-batch focused group passes 12/12 with HTTP rerun outside sandbox",
      "Production-batch/source/source-to-script regression passes 110/110 with HTTP rerun outside sandbox",
      "TypeScript, production build, regenerated codebase map and diff hygiene pass",
      "Read-only design audit identified missing kong-owned-catalog filtering; service/repository/tests now enforce that server-owned adapter constraint",
      "Independent final recheck closed the HTTP guard coverage gap with P0=P1=P2=P3=0",
    ],
    blockers: [
      "Curated Kong source feed is preserved in draft PR kong-nightlife#117, but its HTTP reader and production composition are not yet connected here",
      "No durable scheduler/cursor loop is configured; this route is operator-triggered only",
      "HeyGen, render admission, spend, publishing, migrations and deployment remain separately blocked",
    ],
    nextAction: "Keep PR #173 draft and unmerged; next connect a fail-closed HTTP reader to kong-nightlife#117 and add the durable scheduler/cursor loop.",
  },
  {
    id: "ams-agent-kong-source-scheduler",
    title: "Production KONG source reader and scheduler",
    owner: "AI Media Studio source automation squad",
    state: "review",
    branch: "codex/ai-media-studio-kong-http-scheduler",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/174",
    baseBranch: "codex/ai-media-studio-source-to-batch-automation",
    headBranch: "codex/ai-media-studio-kong-http-scheduler",
    commit: "0224c8d7",
    acceptance: [
      "The exact curated KONG HTTPS feed is DNS-pinned, TLS-hostname verified, redirect-free and JSON/body/cursor bounded",
      "One tenant-scoped orchestration row persists the server cursor with SKIP LOCKED claims, leases, fencing and safe retry recovery",
      "A production-only 15-minute loop resumes source pages without accepting browser endpoint or cursor configuration",
      "Exact curated KONG content is content-hash attested and may prepare deterministic draft scripts only after a complete feed cycle",
      "No HeyGen, secret resolution, render, outbox, spend, publishing, migration or deployment capability is invoked",
    ],
    mergeGate: "Keep draft PR #174 stacked on draft PR #173 until the KONG feed dependency/CI is green and the existing PostgreSQL chain is separately approved and rehearsed.",
    evidence: [
      "Focused HTTP reader, scheduler repository, replay and production-loop tests pass",
      "Reader/scheduler/API 38/38, source-to-batch 12/12, Agent Control 6/6, TypeScript, build, map and diff hygiene pass",
      "Independent checker and App QA rechecks report P0=P1=P2=P3=0",
      "Uses the existing ai_media_orchestration_runs schema; no migration is added or applied",
    ],
    blockers: [
      "The upstream curated feed remains unmerged in kong-nightlife#117 and KONG baseline lightweight checks need a separate repair",
      "No staging migration/restart/recovery evidence or Replit deployment approval exists",
      "HeyGen verification, quote, one-video, 5x10 spend and publishing approvals remain separate",
    ],
    nextAction: "Close checker/App QA findings, save the stacked draft PR, then clear the separate KONG CI repair before any merge or deployment request.",
  },
  {
    id: "ams-agent-heygen-setup-ux-checkpoint",
    title: "Guided secure HeyGen setup checkpoint",
    owner: "AI Media Studio provider onboarding squad",
    state: "review",
    branch: "codex/ai-media-studio-heygen-setup-ux",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/175",
    baseBranch: "codex/ai-media-studio-kong-http-scheduler",
    headBranch: "codex/ai-media-studio-heygen-setup-ux",
    commit: "3f52c23b",
    acceptance: [
      "Guide the initial 5–10 avatars with exactly ten videos each through one stable setup area",
      "Name AI_MEDIA_STUDIO_SECRET_HEYGEN_API_KEY without accepting, displaying or storing its value",
      "Keep migration, live GET verification, quote, generation, canary, publishing and deployment blocked",
    ],
    mergeGate: "Keep draft PR #175 stacked on draft PR #174 and unmerged; this UI checkpoint authorizes no operational action.",
    evidence: [
      "GitHub verifies open draft PR #175 targets the draft PR #174 branch",
      "Focused client/browser 33/33, TypeScript, build, checker and App QA P0=P1=P2=P3=0",
    ],
    blockers: ["The secret is not stored and every external or state-changing gate remains separately approval-bound"],
    nextAction: "Keep PR #175 draft beneath PR #178; never put the HeyGen key value in chat, HTTP, GitHub or PostgreSQL.",
  },
  {
    id: "ams-agent-production-batch-security-checkpoint",
    title: "Production-batch mutation security checkpoint",
    owner: "AI Media Studio security and release squad",
    state: "review",
    branch: "codex/ai-media-studio-production-batch-route-hardening",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/178",
    baseBranch: "codex/ai-media-studio-heygen-setup-ux",
    headBranch: "codex/ai-media-studio-production-batch-route-hardening",
    commit: "287abacc",
    acceptance: [
      "Authenticate prepare and approve before parsing and require exact trusted same-origin JSON",
      "Reject raw query, ambiguous-body and bounded parser failures before tenant-scoped service or persistence calls",
      "Preserve valid provider-neutral no-spend behavior without provider, render, publishing, migration or deployment effects",
    ],
    mergeGate: "Security review is complete for draft PR #178, but draft PR #174 → #175 → #178 stays stacked and unmerged; every operational gate requires separate explicit approval.",
    evidence: [
      "GitHub verifies open draft PR #178 targets draft PR #175, which targets draft PR #174",
      "Checkpoint 287abacc; App QA 48/48 focused and 56/56 expanded with P0=P1=P2=P3=0",
      "TypeScript, build and diff hygiene pass; rejected requests have zero service/persistence effects",
    ],
    blockers: [
      "1. AI_MEDIA_STUDIO_SECRET_HEYGEN_API_KEY is not stored in the approved deployment secret manager",
      "2. Migration rehearsal/application requires explicit approval",
      "3. Read-only live HeyGen GET verification requires explicit approval",
      "4. An authoritative account-specific maximum quote requires explicit approval",
      "5. Exactly one real generation requires explicit cost and execution approval",
      "6. The initial 5 avatars × 10 videos canary requires a new explicit batch approval",
      "7. Publishing and Replit deployment each require separate explicit approval",
    ],
    nextAction: "Keep PRs #174, #175 and #178 draft/unmerged; clear secret, migration, GET verification, quote, one video, 5 × 10 canary, publishing and deployment one gate at a time.",
  },
  {
    id: "ams-agent-control-checkpoint-pr180",
    title: "Dedicated agent control checkpoint refresh",
    owner: "AI Media Studio control-plane squad",
    state: "review",
    branch: "codex/ai-media-studio-agent-control-checkpoint",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/180",
    baseBranch: "codex/ai-media-studio-production-batch-route-hardening",
    headBranch: "codex/ai-media-studio-agent-control-checkpoint",
    commit: "4bc7da3a",
    acceptance: ["Record the reviewed draft chain without representing open work as merged or deployed"],
    mergeGate: "Draft PR #180 remains unmerged and requires its own GitHub merge decision.",
    evidence: ["Checkpoint commit 4bc7da3a is stacked directly after PR #178"],
    blockers: ["The stacked draft chain has not been merged"],
    nextAction: "Keep the checkpoint in review while the later stacked drafts are evaluated.",
  },
  {
    id: "ams-agent-content-plan-policy-pr181",
    title: "Deterministic content-plan policy",
    owner: "AI Media Studio content policy squad",
    state: "review",
    branch: "codex/ai-media-studio-content-plan-policy",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/181",
    baseBranch: "codex/ai-media-studio-agent-control-checkpoint",
    headBranch: "codex/ai-media-studio-content-plan-policy",
    commit: "b812f837",
    acceptance: ["Expose a deterministic no-spend content plan for the initial creator batch"],
    mergeGate: "Draft PR #181 remains unmerged pending GitHub review of the stacked chain.",
    evidence: ["Checkpoint commit b812f837 is stacked directly after PR #180"],
    blockers: ["No merge, generation, publishing or deployment authority exists"],
    nextAction: "Preserve the reviewed policy while later launch-profile work remains stacked.",
  },
  {
    id: "ams-agent-launch-profile-pr182",
    title: "Initial launch profile",
    owner: "AI Media Studio launch planning squad",
    state: "review",
    branch: "codex/ai-media-studio-launch-plan-profile",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/182",
    baseBranch: "codex/ai-media-studio-content-plan-policy",
    headBranch: "codex/ai-media-studio-launch-plan-profile",
    commit: "f1fe9bda",
    acceptance: ["Centralize the exact 5–10 creators and ten videos per creator launch bounds"],
    mergeGate: "Draft PR #182 remains unmerged pending review of its base PRs.",
    evidence: ["Checkpoint commit f1fe9bda is stacked directly after PR #181"],
    blockers: ["The launch profile grants no provider, spend, publishing or deployment permission"],
    nextAction: "Use the profile as the single no-spend planning contract while the chain is reviewed.",
  },
  {
    id: "ams-agent-dashboard-published-metric-pr183",
    title: "Confirmed publishing dashboard metric",
    owner: "AI Media Studio dashboard squad",
    state: "review",
    branch: "codex/ai-media-studio-dashboard-published-metric",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/183",
    baseBranch: "codex/ai-media-studio-launch-plan-profile",
    headBranch: "codex/ai-media-studio-dashboard-published-metric",
    commit: "c465fa71",
    acceptance: ["Report confirmed publishing totals without claiming that publishing is authorized"],
    mergeGate: "Draft PR #183 remains unmerged pending review of the stacked chain.",
    evidence: ["Checkpoint commit c465fa71 is stacked directly after PR #182"],
    blockers: ["Publishing remains separately approval-bound and disabled"],
    nextAction: "Keep the metric read-only until publishing authority and runtime evidence exist.",
  },
  {
    id: "ams-agent-reusable-script-assets-pr184",
    title: "Reusable script assets",
    owner: "AI Media Studio script library squad",
    state: "review",
    branch: "codex/ai-media-studio-reusable-script-assets",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/184",
    baseBranch: "codex/ai-media-studio-dashboard-published-metric",
    headBranch: "codex/ai-media-studio-reusable-script-assets",
    commit: "4f9992ea",
    acceptance: ["Persist tenant-safe reusable script variants without invoking a video provider"],
    mergeGate: "Draft PR #184 remains unmerged pending GitHub review and its inherited bases.",
    evidence: ["Checkpoint commit 4f9992ea is stacked directly after PR #183"],
    blockers: ["Provider calls, spend, publishing, migrations and deployment remain blocked"],
    nextAction: "Keep reusable assets in review and preserve their no-provider boundary.",
  },
  {
    id: "ams-agent-provider-neutral-persona-pr185",
    title: "Provider-neutral roster persona activation",
    owner: "AI Media Studio creator platform squad",
    state: "review",
    branch: "codex/ai-media-studio-provider-neutral-persona-activation",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/185",
    baseBranch: "codex/ai-media-studio-reusable-script-assets",
    headBranch: "codex/ai-media-studio-provider-neutral-persona-activation",
    commit: "90bae351",
    gates: {
      checker: { status: "passed", evidence: ["Independent checker reported P0=P1=P2=P3=0 for checkpoint 90bae351"] },
      appQa: { status: "passed", evidence: ["App QA reported P0=P1=P2=P3=0 for checkpoint 90bae351"] },
      ci: { status: "pending", evidence: ["GitHub statusCheckRollup did not report a completed CI check"] },
      human: { status: "pending", evidence: ["Draft PR #185 is open and unmerged"] },
    },
    acceptance: ["Provision schema-valid provider-neutral starter personas and repair exact roster replays without provider I/O"],
    mergeGate: "Draft PR #185 remains unmerged pending checker, App QA, CI and human merge gates.",
    evidence: ["Checkpoint commit 90bae351 is stacked directly after PR #184"],
    blockers: ["The draft chain is unmerged; live provider verification, spend, publishing, migrations and deployment remain separately blocked"],
    nextAction: "Complete independent review evidence; do not call HeyGen or authorize spend.",
  },
  {
    id: "ams-agent-staging-migrations",
    title: "Ordered staging migration and restart rehearsal",
    owner: "App QA + database release gate",
    state: "blocked",
    branch: "codex/ai-media-studio-staging-rehearsal-runbook",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/118",
    acceptance: [
      "Backup and ordered migrations complete in staging",
      "Restart, contention and evidence-preserving rollback are rehearsed",
      "No warning or failure remains in App QA",
    ],
    mergeGate: "Requires reviewed composition, staging database access and explicit approval before applying migrations.",
    evidence: ["Draft PR #118", "PR30 no-go staging runbook prepared", "Draft PR #131 preserves the exact 22-pair manifest and PR1 provenance", "PR16A/PR16B checker and App QA gates are clean", "No migration has been applied"],
    blockers: ["The exact stacked PR chain is not merged", "Named staging target, backup/restore proof and explicit rehearsal approval are absent"],
    nextAction: "Finish and review the durable script-batch workbench, then request separate approval for one named restored-staging rehearsal; do not apply SQL automatically.",
  },
  {
    id: "ams-agent-one-video-sandbox",
    title: "One-video HeyGen sandbox",
    owner: "Robert + AI Media Studio release gate",
    state: "blocked",
    branch: null,
    pullRequestUrl: null,
    acceptance: [
      "Real credential, quota, billing and callback behavior are verified",
      "One vertical MP4 reaches owned storage and authenticated delivery",
      "Actual cost and rollback evidence are recorded",
    ],
    mergeGate: "Robert approves the exact estimated cost and one provider generation after staging passes.",
    evidence: [],
    blockers: ["Real HeyGen credentials and quota are not verified", "Spend approval has not been granted"],
    nextAction: "Do not call HeyGen yet; finish composition and staging evidence first.",
  },
  {
    id: "ams-agent-five-by-ten-canary",
    title: "Initial 5 avatars × 10 videos canary",
    owner: "AI Media Studio launch squad",
    state: "backlog",
    branch: null,
    pullRequestUrl: null,
    acceptance: [
      "Exactly five verified avatars receive ten approved scripts each",
      "Budget, concurrency, quality, ingest and publishing queues remain within policy",
      "Failures stop safely before expanding toward 100 videos",
    ],
    mergeGate: "One-video sandbox passes, Robert approves the batch cost, and App QA reports no warning or failure.",
    evidence: ["Current no-spend roster preview already plans exactly 50 slots"],
    blockers: ["Sandbox and human launch approval are pending"],
    nextAction: "Keep all 50 slots not queued until the preceding gates are complete.",
  },
];

export function createAiMediaStudioAgentSnapshot(
  now: () => Date = () => new Date(),
  sourceScheduler?: SourceSyncTask | "unavailable",
): AiMediaStudioAgentSnapshot {
  const observedAt = now().toISOString();
  const visibleItems = workItems.map((item) => item.id === "ams-agent-kong-source-scheduler"
    ? schedulerWorkItem(item, sourceScheduler)
    : item).map(materializeWorkItem);
  const counts = {
    review: visibleItems.filter((item) => item.state === "review").length,
    merged: visibleItems.filter((item) => item.state === "merged").length,
    running: visibleItems.filter((item) => item.state === "running").length,
    ready: visibleItems.filter((item) => item.state === "ready").length,
    blocked: visibleItems.filter((item) => item.state === "blocked").length,
    backlog: visibleItems.filter((item) => item.state === "backlog").length,
  };
  const status = counts.running > 0
    ? "working"
    : counts.review > 0 || counts.ready > 0
      ? "awaiting_human"
      : counts.blocked > 0
        ? "blocked"
        : "idle";
  return aiMediaStudioAgentSnapshotSchema.parse({
    agent: {
      id: "ai-media-studio-agent",
      name: "AI Media Studio Agent",
      status,
      route: AI_MEDIA_STUDIO_AGENT_ROUTE,
      mission: "Coordinate the provider-neutral media platform from reviewed code to a safe 5–10-avatar launch, with ten videos per avatar and explicit human gates before spend or deployment.",
    },
    generatedAt: observedAt,
    dataAsOf: AGENT_DATA_AS_OF,
    safety: {
      spendAuthorized: false,
      deploymentAuthorized: false,
      migrationsApplied: false,
      liveProviderCallsEnabled: false,
    },
    launchTarget: {
      minimumAvatars: INITIAL_CREATOR_CANARY_PROFILE.creators.minimum,
      maximumAvatars: INITIAL_CREATOR_CANARY_PROFILE.creators.maximum,
      videosPerAvatar: INITIAL_CREATOR_CANARY_PROFILE.creators.videosPerCreator,
      minimumVideos: INITIAL_CREATOR_CANARY_PROFILE.slots.minimum,
      maximumVideos: INITIAL_CREATOR_CANARY_PROFILE.slots.maximum,
    },
    summary: { total: visibleItems.length, ...counts },
    workItems: visibleItems,
  });
}

function materializeWorkItem(item: AiMediaStudioAgentWorkItem): AiMediaStudioAgentWorkItem {
  return {
    ...item,
    baseBranch: item.baseBranch ?? null,
    headBranch: item.headBranch ?? item.branch,
    ...(item.gates ? {
      gates: {
        checker: { ...item.gates.checker, evidence: [...item.gates.checker.evidence] },
        appQa: { ...item.gates.appQa, evidence: [...item.gates.appQa.evidence] },
        ci: { ...item.gates.ci, evidence: [...item.gates.ci.evidence] },
        human: { ...item.gates.human, evidence: [...item.gates.human.evidence] },
      },
    } : {}),
    harness: item.harness ?? null,
    worktree: item.worktree ?? null,
    heartbeatAt: item.heartbeatAt ?? null,
    handoff: item.handoff ?? null,
    commit: item.commit ?? null,
    evidenceLinks: item.evidenceLinks ?? (item.pullRequestUrl ? [item.pullRequestUrl] : []),
    ...(item.runtime ? { runtime: { ...item.runtime, evidence: [...item.runtime.evidence] } } : {}),
    acceptance: [...item.acceptance],
    evidence: [...item.evidence],
    blockers: [...item.blockers],
  };
}

function schedulerWorkItem(item: AiMediaStudioAgentWorkItem, task?: SourceSyncTask | "unavailable"): AiMediaStudioAgentWorkItem {
  const runtimeState = task === "unavailable" ? "unavailable" : task?.status ?? "not_initialized";
  const stopped = runtimeState === "dead_letter" || runtimeState === "unavailable" || runtimeState === "not_initialized";
  const evidence = [...item.evidence, `Runtime scheduler state: ${runtimeState}`];
  const runtimeEvidence = [`Runtime scheduler state: ${runtimeState}`];
  if (task && task !== "unavailable") {
    evidence.push(`Durable cursor page ${task.payload.page}; cycle ${task.payload.cycle}; attempts ${task.attempts}/${task.maxAttempts}`);
    runtimeEvidence.push(`Durable cursor page ${task.payload.page}; cycle ${task.payload.cycle}; attempts ${task.attempts}/${task.maxAttempts}`);
    if (task.failureCode) evidence.push(`Safe failure code: ${task.failureCode}`);
    if (task.failureCode) runtimeEvidence.push(`Safe failure code: ${task.failureCode}`);
  }
  return {
    ...item,
    runtime: {
      component: "source_scheduler",
      status: runtimeState,
      health: runtimeState === "dead_letter" ? "attention" : stopped ? "stopped" : "healthy",
      evidence: runtimeEvidence,
    },
    evidence,
    blockers: stopped
      ? [...item.blockers, runtimeState === "dead_letter"
        ? "The durable source scheduler is dead-lettered and requires an operator review before any retry"
        : runtimeState === "unavailable"
          ? "The durable source scheduler status is unavailable; source automation must be treated as stopped"
          : "The durable source scheduler has not initialized; source automation must be treated as stopped"]
      : [...item.blockers],
  };
}
