import {
  AI_MEDIA_STUDIO_AGENT_ROUTE,
  aiMediaStudioAgentSnapshotSchema,
  type AiMediaStudioAgentSnapshot,
  type AiMediaStudioAgentWorkItem,
} from "../../shared/ai-media-studio-agent";

const workItems: readonly AiMediaStudioAgentWorkItem[] = [
  {
    id: "ams-agent-pr27-terminal-evidence",
    title: "HeyGen V3 terminal evidence boundary",
    owner: "AI Media Studio backend squad",
    state: "done",
    branch: "codex/ai-media-studio-heygen-terminal-evidence",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/112",
    acceptance: [
      "Provider-authoritative terminal state is exact-account and credential bound",
      "Completed MP4 ingest uses a renewable provider artifact identity",
      "Committed money is never falsely refunded",
    ],
    mergeGate: "Independent checker and App QA report no P0-P2; PostgreSQL, full suite, typecheck and build pass.",
    evidence: ["PR #112", "PostgreSQL 16: 4/4", "Full suite: 657 passed, 0 failed, 24 skipped of 681", "App QA: P0=0, P1=0, P2=0"],
    blockers: [],
    nextAction: "Keep this slice unmounted until production composition and staging gates pass.",
  },
  {
    id: "ams-agent-pr28-control-pane",
    title: "Dedicated AI Media Studio Agent control pane",
    owner: "AI Media Studio product squad",
    state: "done",
    branch: "codex/ai-media-studio-agent-control",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/115",
    acceptance: [
      "Agents Office exposes one dedicated AI Media Studio Agent",
      "The agent area shows owners, states, PRs, evidence, blockers and merge gates",
      "The pane performs no deployment, spend, migration or provider action",
    ],
    mergeGate: "Focused contracts/UI/routes, TypeScript, build, independent checker and App QA all pass before the draft PR is presented as reviewed.",
    evidence: ["Draft PR #115", "Control 5/5 + HTTP routes 4/4; full suite 662 passed, 0 failed, 24 skipped", "TypeScript and production build pass", "Checker and App QA recheck: P0=P1=P2=0"],
    blockers: [],
    nextAction: "Keep the pane read-only and begin the separately reviewed inert production-composition slice.",
  },
  {
    id: "ams-agent-pr29-production-composition",
    title: "Inert HeyGen V3 production composition",
    owner: "AI Media Studio runtime squad",
    state: "done",
    branch: "codex/ai-media-studio-production-composition",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/116",
    acceptance: [
      "Compose admitted submit, terminal observation and renewable ingest without autostart",
      "Exact account, credential and tenant mismatches fail before provider I/O",
      "Construction performs no database, network, storage or spend action",
    ],
    mergeGate: "Composition tests prove zero construction I/O and fail-closed behavior; no route, timer or loop is mounted.",
    evidence: ["Draft PR #116", "Focused tenant/composition/asset regressions: 29/29", "Full suite: 666 passed, 0 failed, 24 skipped", "Checker and App QA recheck: P0=P1=P2=0"],
    blockers: [],
    nextAction: "Keep the runtime unmounted and prepare the ordered staging migration/restart rehearsal for explicit approval.",
  },
  {
    id: "ams-agent-durable-roster-plan",
    title: "Durable roster to ten-slots-per-avatar bridge",
    owner: "AI Media Studio planning squad",
    state: "done",
    branch: "codex/ai-media-studio-durable-roster-plan-bridge",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/136",
    acceptance: [
      "One 5–10 avatar onboarding transaction creates exactly ten blocked durable slots per avatar",
      "Exact replay is tenant-safe and never duplicates or partially persists a plan",
      "The bridge creates no budget reservation, render job, outbox command, provider call or spend",
    ],
    mergeGate: "Focused and PostgreSQL race/rollback evidence, TypeScript, build, independent checker and App QA must pass before the draft PR is ready.",
    evidence: [
      "Draft PR #131 preserves the reviewed 22-pair migration baseline",
      "Three independent design/security audits selected the existing PR19 plan and slot tables",
      "Focused roster/control checks, authenticated HTTP routes, TypeScript and production build pass",
      "Owned ephemeral PostgreSQL 16 full-chain proof passes 1/1 for 5→50, 10→100, replay, concurrency, tenant isolation and rollback",
      "Independent checker and App QA pass with P0=P1=P2=0 and no change warnings",
      "Draft PR #136 preserves the reviewed checkpoint stacked on draft PR #131",
    ],
    blockers: ["Merge, migration rehearsal, one-video sandbox, batch spend and deployment remain separately blocked"],
    nextAction: "Keep PR #136 unmerged until the stacked chain is reviewed; request separate approvals before staging, HeyGen sandbox, spend or Replit deployment.",
  },
  {
    id: "ams-agent-durable-script-batch",
    title: "Durable production script batch workbench",
    owner: "AI Media Studio content planning squad",
    state: "done",
    branch: "codex/ai-media-studio-durable-script-batch",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/141",
    acceptance: [
      "Exactly ten eligible Kong sources prepare one durable draft script for every blocked slot",
      "Five to ten creators remain grouped into exactly ten no-spend slots each",
      "Replay, source refresh, tenant isolation and partial failure fail closed without duplicate scripts",
      "Legacy generation cannot bypass daily-plan admission, and no provider, budget, render or outbox side effect occurs",
    ],
    mergeGate: "PostgreSQL race/rollback/source-refresh proof, TypeScript, build, independent checker and App QA must pass before a stacked draft PR is ready.",
    evidence: [
      "Draft PR #136 preserves the reviewed durable 5→50 and 10→100 roster-plan checkpoint",
      "Three independent product, operations and architecture audits selected the provider-neutral prepare-only batch slice",
      "Backend and frontend makers had non-overlapping ownership in an isolated worktree",
      "Focused/UI/HTTP tests, TypeScript, production build and the refreshed codebase map pass",
      "Owned PostgreSQL 16 applied the exact 22-pair chain and proved 5→50, 10→100, replay/concurrency, tenant isolation, source refresh, rollback and zero launch side effects",
      "Independent checker recheck is P0=P1=P2=0 after one fixed UI error-message finding",
      "App QA is P0=P1=P2=0 after the optional GET preserved safe server error text",
      "Mergeable draft PR #141 is stacked on reviewed draft PR #136",
    ],
    blockers: ["Merge, migration rehearsal, provider sandbox, batch spend and deployment remain separately blocked", "The inherited Clippers chunk warning blocks deployment; no deployment is requested"],
    nextAction: "Keep draft PR #141 unmerged while the stacked chain is reviewed; request separate approval before staging, HeyGen sandbox, spend or Replit deployment.",
  },
  {
    id: "ams-agent-launch-readiness",
    title: "Durable script review and launch readiness",
    owner: "AI Media Studio content approval squad",
    state: "done",
    branch: "codex/ai-media-studio-launch-readiness",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/144",
    acceptance: [
      "Every selected 5–10 × 10 creative exposes and seals Video Title, angle, hook, script, CTA, caption, hashtags and SEO",
      "One tenant-locked whole-batch transition approves only scripts and their selected/current variants",
      "Approval revalidates exact batch, source content, status, rights and moderation without creating launch or provider work",
    ],
    mergeGate: "Focused, HTTP and PostgreSQL proof, TypeScript, build, independent checker, security and App QA must pass before the draft GitHub checkpoint.",
    evidence: [
      "Draft PR #144 is stacked on draft PR #141",
      "Focused checks 20/20; authenticated HTTP routes 2/2; owned PostgreSQL 16 exact-chain harness 1/1",
      "Full suite: 722 passed, one inherited PR26 wording-regex failure and 40 controlled PostgreSQL-only skips of 763",
      "TypeScript and production build pass",
      "Independent checker, security and App QA: P0=P1=P2=P3=0",
    ],
    blockers: [
      "Merge, migration rehearsal, governance and launch authority, one-video sandbox, batch spend and deployment remain separately blocked",
      "The inherited Clippers chunk warning blocks deployment; no deployment is requested",
    ],
    nextAction: "Keep draft PR #144 unmerged and implement the offline authority/admission preflight as a separately reviewed slice; do not call HeyGen or authorize spend.",
  },
  {
    id: "ams-agent-offline-launch-preflight",
    title: "Offline launch preflight and exact approval bridge",
    owner: "AI Media Studio launch safety squad",
    state: "done",
    branch: "codex/ai-media-studio-offline-launch-preflight",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/146",
    acceptance: [
      "The approved 5–10 × 10 batch is revalidated from exact tenant, source, creative and approval metadata",
      "One authenticated read-only observation reports all 14 launch gates without minting authority",
      "Creator confirmations and approval success belong only to the exact visible batch identity",
      "No provider call, budget reservation, render, outbox, migration, deployment or spend is authorized",
    ],
    mergeGate: "Focused, HTTP, PostgreSQL, TypeScript, build, independent checker, security and App QA must pass with no P0-P3 before the draft checkpoint is ready.",
    evidence: [
      "Draft PR #146 is stacked on draft PR #144",
      "Focused checks 54/54; authenticated HTTP routes 2/2; owned PostgreSQL 16 exact 22-pair chain 1/1",
      "Full suite: 749 passed, one inherited PR26 wording-regex failure and 41 controlled skips of 791",
      "TypeScript and production build pass",
      "Independent checker, security and App QA final gates: P0=P1=P2=P3=0",
    ],
    blockers: [
      "Merge, migration rehearsal, live provider verification, authority/evidence, one-video sandbox, batch spend and deployment remain separately blocked",
      "The inherited Clippers chunk warning blocks deployment; no deployment is requested",
    ],
    nextAction: "Keep draft PR #146 unmerged; obtain separate approvals before staging, a one-video HeyGen sandbox, any spend, or Replit deployment.",
  },
  {
    id: "ams-agent-one-video-sandbox-readiness",
    title: "One-video sandbox readiness packet and offline runtime proof",
    owner: "AI Media Studio sandbox readiness squad",
    state: "done",
    branch: "codex/ai-media-studio-one-video-sandbox-readiness",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/147",
    acceptance: [
      "One explicitly selected slot from a genuine approved 5 × 10 batch exposes an authenticated read-only 9:16 readiness packet",
      "A disposable exact-chain PostgreSQL rehearsal drives exactly one slot through fake submit, terminal completion and durable owned ingest with zero publishing",
      "Generation, provider submission, admission, spend and every effect remain false; no real provider, migration or deployment action occurs",
    ],
    mergeGate: "Focused, HTTP, browser, PostgreSQL, TypeScript, build, independent checker, security and App QA pass with P0=P1=P2=P3=0 before the draft checkpoint is ready.",
    evidence: [
      "Draft PR #147 is stacked on draft PR #146",
      "A genuine approved 5 × 10 fixture keeps all 50 scripts approved while exactly one selected slot completes the fake-provider runtime rehearsal",
      "Focused 59/59; authenticated routes 4/4; browser 1/1; owned PostgreSQL 16 exact 22-pair chain 1/1",
      "Full suite: 811/812 passed; the only failure is the inherited PR26 wording regex. TypeScript, production build and diff hygiene pass",
      "Independent checker, security and App QA final gates: P0=P1=P2=P3=0 after one P3 test correction",
    ],
    blockers: [
      "Merge, named staging migration rehearsal, live HeyGen credential/account/quota verification, maximum quote, owned storage, callbacks and explicit one-video cost approval remain separately blocked",
      "The later 5 × 10 canary spend and Replit deployment require separate approvals; no provider call or spend is authorized",
      "The inherited Clippers chunk warning blocks deployment; no deployment is requested",
    ],
    nextAction: "Keep draft PR #147 unmerged; accept the HeyGen API key only through the approved secret manager plus 5–10 avatar/voice IDs, and do not call HeyGen until live checks and Robert's explicit one-video cost approval pass.",
  },
  {
    id: "ams-agent-static-heygen-onboarding",
    title: "Secure static HeyGen credential and roster onboarding",
    owner: "AI Media Studio provider onboarding squad",
    state: "done",
    branch: "codex/ai-media-studio-heygen-onboarding-readiness",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/148",
    acceptance: [
      "Persist only an approved secret-manager reference and digest, never the HeyGen API key value",
      "Accept 5–10 avatar and voice ID pairs as pending verification and create exactly ten blocked no-spend slots per avatar",
      "Expose authenticated read-only onboarding readiness while pending resources remain inactive and non-selectable",
    ],
    mergeGate: "Static credential, roster, HTTP, browser, PostgreSQL, TypeScript, build, checker, security and App QA evidence must pass with no P0-P3 before the draft checkpoint is ready.",
    evidence: [
      "Draft PR #148 is stacked on draft PR #147",
      "Final App QA targeted run passes 44/44; TypeScript, production build, codebase map and diff hygiene pass",
      "Disposable PostgreSQL 16 exact PR1–PR27 chain plus pending PR28 forward, rotation and rollback guard passes 1/1",
      "Independent checker, security and App QA final gates: P0=P1=P2=P3=0",
    ],
    blockers: [
      "The API key has not been placed in the deployment secret manager and no live HeyGen verification has run",
      "The pending PR28 migration is outside the manifest and unapplied; promotion and application require separate approval",
      "One-video generation, 5 × 10 batch spend, publishing and Replit deployment remain separately blocked",
    ],
    nextAction: "Keep draft PR #148 unmerged; Robert places the API key only in the approved secret manager and supplies 5–10 avatar/voice IDs, then separately approve read-only live verification before any quote or generation.",
  },
  {
    id: "ams-agent-one-video-execution-control",
    title: "Inert one-video verification and execution control",
    owner: "AI Media Studio provider execution squad",
    state: "done",
    branch: "codex/ai-media-studio-one-video-execution-control",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/149",
    acceptance: [
      "Pin one reviewed official HeyGen API profile behind provider-neutral verification and render contracts",
      "Bind credential, avatar, voice, approved script, vertical format and maximum quote to exactly one public slot",
      "Keep verification, quote preparation and human approval distinct while execution, provider calls and spend remain disabled",
      "Define fail-closed handling for credential rotation, stale evidence, ambiguous submit, callback fallback, ingest and actual-cost settlement",
    ],
    mergeGate: "Official-provider documentation audit, focused and PostgreSQL evidence, TypeScript, build, independent checker, security and App QA must pass with no P0-P3 before a stacked draft PR is ready.",
    evidence: [
      "Draft PR #149 is stacked on reviewed draft PR #148",
      "Focused control/client/UI 58/58, one-video control 9/9, isolated browser 1/1, TypeScript and production build pass",
      "Full serial AI Media Studio suite: 804 passed, one inherited PR26 wording-regex failure and 43 controlled skips of 848",
      "Independent checker, security and App QA final gates: P0=P1=P2=P3=0 after the V3 avatar-look correction",
    ],
    blockers: [
      "No API key, live account, avatar look, voice, storage or callback has been verified",
      "Immutable exact static-credential verification and account-specific maximum quote evidence do not exist yet",
      "Provider verification, any migration apply, one-video POST, spend, publishing and Replit deployment require separate approvals",
    ],
    nextAction: "Keep draft PR #149 unmerged; Robert supplies the API key only through the deployment secret manager plus 5–10 avatar-look/voice ID pairs, then separately approve read-only live verification before quote or generation.",
  },
  {
    id: "ams-agent-heygen-verification-evidence",
    title: "Immutable HeyGen V3 verification evidence",
    owner: "AI Media Studio credential verification squad",
    state: "done",
    branch: "codex/ai-media-studio-heygen-verification-evidence",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/154",
    acceptance: [
      "Persist immutable tenant- and credential-version-bound account verification evidence without credential material",
      "Bind every configured avatar resource to an exact HeyGen V3 avatar look and keep parent-group consent/status evidence separate",
      "Bind every configured voice to an exact verified V3 voice response and make rotation stale by construction",
      "Keep provider transport, secret resolution, account activation, migration application, spend and rendering disabled until separate approval",
    ],
    mergeGate: "Draft PR #154 stays unmerged; live verification, migration application, quote, spend, generation and deployment remain separate Robert approvals.",
    evidence: [
      "Draft PR #154 is stacked on draft PR #149 with the PR29 migration outside the manifest and unapplied",
      "Provider 25/25, coordinator 4/4, migration 7/7, disposable PostgreSQL 16 1/1, TypeScript and production build pass",
      "Final checker, security and App QA report P0-P3 clean; full suite records 840 pass, one inherited PR26 mismatch and 44 controlled skips",
    ],
    blockers: [
      "No API key has been placed in the deployment secret manager and no provider request is approved",
      "No live account, avatar look, parent group, voice, quota, wallet or billing evidence exists",
      "Migration application, credential resolution, provider verification, account activation, quote, generation, spend and Replit deployment require separate approvals",
    ],
    nextAction: "Keep draft PR #154 unmerged; Robert places the API key only in the deployment secret manager, provides 5–10 exact avatar-look/voice pairs, then separately approves live read-only verification.",
  },
  {
    id: "ams-agent-one-video-verification-read-model",
    title: "Exact one-video HeyGen verification read model",
    owner: "AI Media Studio read-model squad",
    state: "done",
    branch: "codex/ai-media-studio-one-video-verification-read-model",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/156",
    acceptance: [
      "Project verified state only from the exact immutable PR29 account, avatar-look and voice evidence graph",
      "Fail closed for expiry, credential rotation, tenant or plan mismatch, and incomplete resource evidence",
      "Keep the authenticated endpoint GET-only, redact provider-native identities and leave execute, spend, publishing and every effect disabled",
      "Prove the projection with focused tests and a disposable PostgreSQL 16 integration fixture for the initial 5 avatars × 10 videos shape",
    ],
    mergeGate: "Focused, PostgreSQL, TypeScript, build, independent checker, security and App QA evidence must pass with no P0-P3 before a stacked draft PR is ready.",
    evidence: [
      "Read-only control, data, test and App QA audits identified the exact PR29 evidence projection gap",
      "Focused control and authenticated route checks pass 12/12; disposable PostgreSQL 16 exact 5 x 10 and 10 x 10 proof passes 2/2",
      "TypeScript and production build pass; independent checker, security and App QA are P0-P3 clean",
    ],
    blockers: [
      "The PR29 migration remains pending and unapplied; this read model is stacked after that migration",
      "No API key, live HeyGen verification, quote, spend, generation, publishing or deployment is authorized",
    ],
    nextAction: "Keep this stacked checkpoint unmerged; Robert later supplies the API key only through the secret manager and separately approves live read-only verification.",
  },
  {
    id: "ams-agent-secure-heygen-setup-runtime",
    title: "Guided secure HeyGen setup and explicit verification runtime",
    owner: "Dedicated HeyGen onboarding and verification agents",
    state: "done",
    branch: "codex/ai-media-studio-secure-heygen-setup-runtime",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/161",
    acceptance: [
      "Robert adds the API key only as AI_MEDIA_STUDIO_SECRET_HEYGEN_API_KEY in the deployment secret manager",
      "The browser registers only a fixed allowlisted reference and accepts 5–10 avatar-look and voice pairs for exactly ten blocked videos each",
      "Live verification is a separate explicitly authorized GET-only action with immutable evidence and no generation or spend",
      "The action center shows the current safe next step without requesting or exposing credential material",
    ],
    mergeGate: "Focused, PostgreSQL, TypeScript, build, independent checker, security and App QA evidence must pass before a stacked draft PR is ready.",
    evidence: [
      "Draft PR #161 preserves the secure setup checkpoint on GitHub",
      "Focused setup suite 22/22, PostgreSQL 1/1, browser 1/1 and production build passed",
      "Independent security and App QA reviews report P0=P1=P2=P3=0; checker found no functional P0/P1",
      "Public setup contracts reject API keys, caller-selected secret references and provider account IDs",
    ],
    blockers: [
      "PR28 and PR29 migrations remain pending and unapplied",
      "No live verification call is authorized; quote, generation, spend, publishing and deployment remain separate gates",
      "Draft PR #165 now closes quote-to-human approval binding, but it remains unmerged in the stacked chain",
    ],
    nextAction: "Keep draft PR #161 unmerged; then Robert supplies the secret through the deployment secret manager and the avatar/voice IDs through the guided roster before separately authorizing GET-only verification.",
  },
  {
    id: "ams-agent-quote-bound-human-approval",
    title: "Exact maximum-quote to human-approval binding",
    owner: "Quote authority, schema, security and App QA agents",
    state: "done",
    branch: "codex/ai-media-studio-quote-bound-approval",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/165",
    acceptance: [
      "Robert's decision is durably bound to one exact latest quote, amount, USD currency, expiry and server-derived render specification",
      "A newer quote, changed subject, credential rotation, expiry or tenant mismatch makes the prior approval stale",
      "Legacy unbound approvals never satisfy snapshot, admission or the one-video execution read model",
      "Approval records no provider, secret, reservation, render, outbox, spend, publishing, migration or deployment effect",
    ],
    mergeGate: "Draft PR #165 is open and stacked on PR #161; it must remain unmerged until the dependency chain, checker, security and App QA gates stay green.",
    evidence: [
      "PR #165 binds human approval to exact quote evidence identity, revision, digest, amount, USD currency, expiry and server render-spec digest",
      "Focused suite: 50 passed and 3 optional route tests skipped because the local worktree lacks optional route dependency",
      "Sandbox browser rerun outside sandbox passed 1/1; PR30 isolated PostgreSQL harness passed 1/1; agent control passed 5/5; build passed",
      "The staged diff secret scan found no new secret/token/private-key patterns",
    ],
    blockers: [
      "No authoritative account-specific HeyGen quote provider is installed, so no amount may be fabricated",
      "PR28 and PR29 migrations remain pending and unapplied",
      "No generation, spend, publishing, migration apply or Replit deployment is authorized",
    ],
    nextAction: "Keep draft PR #165 unmerged; next implement an authoritative account-specific quote provider and keep generation, spend, publishing, migration apply and Replit deployment behind separate Robert approvals.",
  },
  {
    id: "ams-agent-heygen-account-maximum-quote",
    title: "Fail-closed HeyGen account maximum-quote adapter",
    owner: "Quote provider, documentation, security and review agents",
    state: "done",
    branch: "codex/ai-media-studio-heygen-account-quote",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/166",
    acceptance: [
      "Accept only an exact server-locked subject, render specification, account, credential version, database time and idempotency key",
      "Never convert public rates, script length or wallet balance into authoritative quote evidence",
      "Return an explicit unavailable outcome when HeyGen provides no account-specific pre-generation quote",
      "Perform no network, secret, provider POST, reservation, render, outbox, spend, publishing, migration or deployment effect",
    ],
    mergeGate: "Draft PR #166 stays stacked on PR #165; a future quoted outcome requires authoritative account terms and a separately reviewed durable quote coordinator.",
    evidence: [
      "Official HeyGen user, pricing, create-video and documentation-index sources expose no pre-generation quote endpoint",
      "Strict locked-request and quote-outcome suite passes 22/22",
      "Independent checker reports P0=P1=P2=P3=0 and production build passes",
      "PR #165 production approval wiring was corrected and independently rechecked before PR #166 was opened",
    ],
    blockers: [
      "Authoritative account-specific HeyGen pre-generation quote terms remain unavailable",
      "No maximum-quote evidence may be minted from public prices or estimated script duration",
      "Generation, spend, publishing, migration apply and Replit deployment remain separately blocked",
    ],
    nextAction: "Keep draft PR #166 unmerged; obtain authoritative account quote terms before adding the durable quote coordinator, then separately approve one live GET-only verification and one-video sandbox.",
  },
  {
    id: "ams-agent-quote-readiness",
    title: "Provider-neutral maximum-quote readiness",
    owner: "Quote readiness maker, checker and App QA agents",
    state: "done",
    branch: "codex/ai-media-studio-quote-readiness",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/168",
    acceptance: [
      "Launch preflight and exact one-video control expose the same strict readiness states and safe next actions",
      "Exact quote evidence cannot be impersonated by capability or explanatory readiness",
      "HeyGen reports account-specific terms required without a provider call, secret resolution or estimated cost",
      "No quote request, approval, reservation, render, outbox, spend, publishing, migration or deployment effect is introduced",
    ],
    mergeGate: "Focused contracts, repositories, client and UI tests, production build, independent checker and App QA must pass before the stacked draft PR is ready.",
    evidence: [
      "Both read models use one provider-neutral capability registry and strict public quote-readiness schema",
      "The exact approval control remains enabled only by current server-attested quote and render-spec evidence",
      "Production HeyGen composition uses the inert fail-closed adapter from draft PR #166",
      "Draft PR #168 preserves the checkpoint; independent checker and App QA report P0=P1=P2=P3=0 and the production build passes",
    ],
    blockers: [
      "Authoritative account-specific HeyGen pre-generation quote terms remain unavailable",
      "The one-shot executor remains uninstalled and provider I/O remains disabled",
      "Generation, spend, publishing, migration apply and Replit deployment remain separately blocked",
    ],
    nextAction: "Keep draft PR #168 unmerged; obtain authoritative account terms before implementing durable quote acquisition, then request separate approvals for live verification and one-video sandbox generation.",
  },
  {
    id: "ams-agent-one-video-held-admission",
    title: "One-video held admission and expiry safety",
    owner: "Admission, database safety, authorization, UI, security and App QA agents",
    state: "running",
    branch: "codex/ai-media-studio-one-video-held-admission",
    pullRequestUrl: null,
    acceptance: [
      "An authenticated personal-workspace operator can request one exact held admission using public CAS keys only",
      "The server derives all internal identifiers, authority, budget, versions, money and expiry before a locked revalidation",
      "Admission creates only a reserved budget record plus sealed render/outbox work in held states",
      "Expired never-activated held admissions release budget exactly once through reviewed database evidence",
      "Provider activation, secret resolution, external spend, rendering, publishing, migration apply and deployment remain unavailable",
    ],
    mergeGate: "Pending PR31 expiry migration, contracts, PostgreSQL races, auth-first routes, UI, independent security/checker and App QA must pass before the stacked draft PR is ready.",
    evidence: [
      "Existing DrizzleDailyAdmissionRepository already revalidates exact authority and creates atomic held work without provider I/O",
      "Multi-agent audit found the missing safe-expiry transition and prohibited mounting admission until it is represented durably",
    ],
    blockers: [
      "Pending migration PR31 must be reviewed but must not be applied without separate approval",
      "Authoritative quote terms, live verification and a current authority snapshot are still absent in production",
      "Provider activation and one-shot workers remain deliberately unmounted",
    ],
    nextAction: "Implement and review held-expiry evidence, then mount one strict admission-only workflow; never activate or call HeyGen in this checkpoint.",
  },
  {
    id: "ams-agent-staging-migrations",
    title: "Ordered staging migration and restart rehearsal",
    owner: "App QA + database release gate",
    state: "blocked",
    branch: "codex/ai-media-studio-staging-rehearsal-runbook",
    pullRequestUrl: "https://github.com/robertmanzanillag-jpg/blackops-reminder/pull/118",
    acceptance: [
      "Backup and ordered migrations complete in staging",
      "Restart, contention and evidence-preserving rollback are rehearsed",
      "No warning or failure remains in App QA",
    ],
    mergeGate: "Requires reviewed composition, staging database access and explicit approval before applying migrations.",
    evidence: ["Draft PR #118", "PR30 no-go staging runbook prepared", "Draft PR #131 preserves the exact 22-pair manifest and PR1 provenance", "PR16A/PR16B checker and App QA gates are clean", "No migration has been applied"],
    blockers: ["The exact stacked PR chain is not merged", "Named staging target, backup/restore proof and explicit rehearsal approval are absent"],
    nextAction: "Finish and review the durable script-batch workbench, then request separate approval for one named restored-staging rehearsal; do not apply SQL automatically.",
  },
  {
    id: "ams-agent-one-video-sandbox",
    title: "One-video HeyGen sandbox",
    owner: "Robert + AI Media Studio release gate",
    state: "blocked",
    branch: null,
    pullRequestUrl: null,
    acceptance: [
      "Real credential, quota, billing and callback behavior are verified",
      "One vertical MP4 reaches owned storage and authenticated delivery",
      "Actual cost and rollback evidence are recorded",
    ],
    mergeGate: "Robert approves the exact estimated cost and one provider generation after staging passes.",
    evidence: [],
    blockers: ["Real HeyGen credentials and quota are not verified", "Spend approval has not been granted"],
    nextAction: "Do not call HeyGen yet; finish composition and staging evidence first.",
  },
  {
    id: "ams-agent-five-by-ten-canary",
    title: "Initial 5 avatars × 10 videos canary",
    owner: "AI Media Studio launch squad",
    state: "backlog",
    branch: null,
    pullRequestUrl: null,
    acceptance: [
      "Exactly five verified avatars receive ten approved scripts each",
      "Budget, concurrency, quality, ingest and publishing queues remain within policy",
      "Failures stop safely before expanding toward 100 videos",
    ],
    mergeGate: "One-video sandbox passes, Robert approves the batch cost, and App QA reports no warning or failure.",
    evidence: ["Current no-spend roster preview already plans exactly 50 slots"],
    blockers: ["Sandbox and human launch approval are pending"],
    nextAction: "Keep all 50 slots not queued until the preceding gates are complete.",
  },
];

export function createAiMediaStudioAgentSnapshot(
  now: () => Date = () => new Date(),
): AiMediaStudioAgentSnapshot {
  const counts = {
    done: workItems.filter((item) => item.state === "done").length,
    running: workItems.filter((item) => item.state === "running").length,
    ready: workItems.filter((item) => item.state === "ready").length,
    blocked: workItems.filter((item) => item.state === "blocked").length,
    backlog: workItems.filter((item) => item.state === "backlog").length,
  };
  return aiMediaStudioAgentSnapshotSchema.parse({
    agent: {
      id: "ai-media-studio-agent",
      name: "AI Media Studio Agent",
      status: "working",
      route: AI_MEDIA_STUDIO_AGENT_ROUTE,
      mission: "Coordinate the provider-neutral media platform from reviewed code to a safe 5–10-avatar launch, with ten videos per avatar and explicit human gates before spend or deployment.",
    },
    generatedAt: now().toISOString(),
    safety: {
      spendAuthorized: false,
      deploymentAuthorized: false,
      migrationsApplied: false,
      liveProviderCallsEnabled: false,
    },
    launchTarget: {
      minimumAvatars: 5,
      maximumAvatars: 10,
      videosPerAvatar: 10,
      minimumVideos: 50,
      maximumVideos: 100,
    },
    summary: { total: workItems.length, ...counts },
    workItems: workItems.map((item) => ({ ...item, acceptance: [...item.acceptance], evidence: [...item.evidence], blockers: [...item.blockers] })),
  });
}
